version: "3.8"
services:
  db:
    image: mysql:8.0.27
    container_name: db
    ports: 
      - 3306:3306
    environment:
      MYSQL_USER: karasawa
      MYSQL_PASSWORD: karasawa
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - "./driver/mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - test_network
networks:
  test_network:
