name: Deploy

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/150158199877/locations/global/workloadIdentityPools/my-pool2/providers/my-provider2
          service_account: my-service-account@my-project.iam.gserviceaccount.com

      - name: Prepare gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Execute Cloud Build
        # run: |
        #   gcloud builds submit --config cloudbuild.yaml \
        #   --substitutions=_TAG_NAME="${TAG_NAME}"
        run: |
          gcloud compute instances list
        env:
          TAG_NAME: 'latest'
