name: Deploy

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  TAG_NAME: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v1
      #   with:
      #     workload_identity_provider: projects/150158199877/locations/global/workloadIdentityPools/my-pool2/providers/my-provider2
      #     service_account: my-service-account@my-project.iam.gserviceaccount.com

      - name: Prepare gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      # - name: Prepare gcloud CLI
      #   uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate to GKE
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: autopilot-cluster-1
          location: asia-northeast2
          credentials: ${{ secrets.SA_KEY }}

      # - name: Execute Cloud Build
      #   run: |
      #     gcloud builds submit --config cloudbuild.yaml \
      #     --substitutions=_TAG_NAME="${TAG_NAME}"
      #   env:
      #     TAG_NAME: 'latest'

      - name: Get Secret
        run: |-
          gcloud secrets versions access latest --secret=kube-demo --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Image Build
        run: |-
          docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/test-repository/kube:${{ env.TAG_NAME }} .

      - name: Image Push
        run: |-
          docker push asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/test-repository/kube:${{ env.TAG_NAME }}

      # - name: Set Kustomize
      #   run: |-
      #     curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
      #     chmod u+x ./kustomize

      - name: Deploy
        run: kubectl apply -f ./kubernetes/manifest.yaml
