name: learning GitHub Actions
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: false
env:
  env_1: karasawa
jobs:
  test_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: hello_world
        run: echo "Hello World1 ${{ secrets.TEST_SECRET }} && echo " env is ${{ env.env_1 }}"
  test_job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: hello_world
        run: echo "Hello World2 ${{ github.event.inputs.name }}"
